export const dealStages = ['Draft', 'Submitted', 'Under Review', 'Approved', 'Published', 'In Negotiation', 'Closed'];

export const sampleDeals = [
  {
    id: 'sample-saas-growth',
    title: 'B2B SaaS Workflow Automation Platform',
    industry: 'Technology',
    location: 'Singapore',
    type: 'sell_equity',
    valuation: 18500000,
    equityOffered: 35,
    revenue: [4200000, 6100000, 8400000],
    ebitda: 2100000,
    netProfit: 1400000,
    growthRate: 37,
    roiEstimate: 18,
    matchScore: 92,
    riskScore: 24,
    growthScore: 88,
    status: 'Published',
    summary: 'Recurring revenue SaaS company with regional enterprise clients and strong net retention.',
    marketPosition: 'Category leader in mid-market workflow automation across ASEAN.',
    strategicReason: 'Founder seeks strategic buyer or growth capital to expand into Japan and Australia.',
    sellerUid: 'sample-seller',
  },
  {
    id: 'sample-healthcare-chain',
    title: 'Multi-site Diagnostic Clinic Chain',
    industry: 'Healthcare',
    location: 'Vietnam',
    type: 'sell_100',
    valuation: 32000000,
    equityOffered: 100,
    revenue: [7600000, 10200000, 13800000],
    ebitda: 3600000,
    netProfit: 2300000,
    growthRate: 29,
    roiEstimate: 14,
    matchScore: 86,
    riskScore: 31,
    growthScore: 80,
    status: 'Published',
    summary: 'Profitable diagnostics network with contracted corporate customers and expansion permits.',
    marketPosition: 'Recognized regional provider with defensible locations and physician referral base.',
    strategicReason: 'Shareholders want a majority or full exit after completing operational integration.',
    sellerUid: 'sample-seller',
  },
  {
    id: 'sample-logistics',
    title: 'Cold-chain Logistics Operator',
    industry: 'Logistics',
    location: 'Thailand',
    type: 'fundraising',
    valuation: 26000000,
    equityOffered: 22,
    revenue: [9100000, 12400000, 16900000],
    ebitda: 2800000,
    netProfit: 1600000,
    growthRate: 36,
    roiEstimate: 16,
    matchScore: 81,
    riskScore: 38,
    growthScore: 84,
    status: 'In Negotiation',
    summary: 'Temperature-controlled logistics platform serving healthcare, food, and modern retail.',
    marketPosition: 'High-utilization fleet with warehouse coverage near major ports and airports.',
    strategicReason: 'Capital raise to finance additional warehouses and automated routing technology.',
    sellerUid: 'sample-seller',
  },
];

export const kycChecklist = [
  'Email OTP verified',
  'Government ID or passport uploaded',
  'Face verification completed',
  'Business license uploaded',
  'Shareholder structure declared',
];
